name: "Deploy to NuGet"

on:
  push:
    branches: [ main ]
    
jobs:
  publish:
    name: Publish NuGet
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x
      - name: publish on version change
        id: publish_nuget
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: src/LawBook/LawBook.csproj
          PACKAGE_NAME: LawBook
          VERSION_FILE_PATH: src/LawBook/LawBook.csproj
          VERSION_REGEX: ^\s*<Version>(.*)<\/Version>\s*$
          TAG_COMMIT: true
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          NUGET_SOURCE: https://api.nuget.org
          INCLUDE_SYMBOLS: false
